Fix the lxc-host-image-demo build error with R-Car BSP 5.5
The lxc-host-image-demo can't build after BSP 5.5 merged.

Error message as a follow:

ERROR: Nothing PROVIDES 'linux-renesas' (but mc:agl-container-guest:
/../gstreamer1.0-plugins-bad_1.16.3.bb DEPENDS on or otherwise requires it)
linux-renesas was skipped: Set PREFERRED_PROVIDER_virtual/kernel to linux-renesas to enable it
Missing or unbuildable dependency chain was:
['cluster-refgui', 'qtmultimedia', 'gstreamer1.0-plugins-bad', 'linux-renesas']
ERROR: Required build target 'guest-image-cluster-demo' has no buildable providers.
Missing or unbuildable dependency chain was:
['guest-image-cluster-demo', 'cluster-refgui', 'qtmultimedia', 'gstreamer1.0-plugins-bad', 'linux-renesas']

This patch fix this build error.

 Bug-AGL: SPEC-4129

Signed-off-by: Naoto Yamaguchi <naoto.yamaguchi@aisin.co.jp>
Change-Id: I0284a70aa38f855eb21e83e8c91e2df5a36cd7ef